{{- $devRead := "DeveloperRead" -}}
{{- $devWrite := "DeveloperWrite" -}}

{{- range .Values.topics }}

{{- $stage := include "extract-stage-name" $ | trim -}}
{{- $principalName := printf "kafka_user_%s_%s" $.Values.teamname $stage }}

apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: {{ printf "%s_%s_%s" $principalName $devRead .name }}
  namespace: {{ $.Values.namespace }}

spec:
  principal:
    type: group
    name: {{ $principalName }}
  role: {{ $devRead }}
  resourcePatterns:
    - name: {{ .name }}
      resourceType: Topic
      patternType: LITERAL
  #clustersScopeByIds:
  #  kafkaClusterId: 
    #schemaRegistryClusterId:
    #ksqlClusterId:
    #connectClusterId:
---
{{- end }}