{{- range $topic := .Values.topics }}
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  namespace: {{ $.Values.namespace }}
spec:
  partitionCount: {{ $topic.partitions }}
  replicas: {{ $topic.replicas }}
  configs:
    {{- toYaml $topic.configs | nindent 4 }}
  kafkaClusterRef:
    name: {{ $.Values.kafka.name }}
    namespace: {{ $.Values.namespace }}
---
{{- end }}