{{- range $topic := .Values.topics }}
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  namespace: {{ $.Values.namespace }}
spec:
  partitionCount: {{ $topic.partitions }}
  replicas: {{ $topic.replicas }}
  configs:
    {{- range $key, $value := $topic.configs }}
    {{ $key }}: {{ if regexMatch "^[+-]?([0-9]+(\\.[0-9]+)?|\\.[0-9]+)([eE][+-]?[0-9]+)?$" (printf "%v" $value) }}{{ printf "%.0f" $value | quote}}{{ else }}{{ $value }}{{ end }}
    {{- end }}
  kafkaClusterRef:
    name: {{ $.Values.kafka.name }}
    namespace: {{ $.Values.namespace }}
{{- end }}